// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Confetti Button",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Confetti Button",
            targets: ["AppModule"],
            bundleIdentifier: "sedamentalist.Todo-App",
            teamIdentifier: "S8LX4NFS36",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .star),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readWrite),
                .fileAccess(.downloadsFolder, mode: .readWrite),
                .fileAccess(.pictureFolder, mode: .readWrite),
                .fileAccess(.musicFolder, mode: .readWrite),
                .fileAccess(.moviesFolder, mode: .readWrite)
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/simibac/ConfettiSwiftUI.git", .exact("1.1.0"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "ConfettiSwiftUI", package: "confettiswiftui")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)